# Generated by Django 4.0 on 2021-12-22 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_remove_images_created_at_remove_images_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='image',
            new_name='file',
        ),
        migrations.AddField(
            model_name='posts',
            name='file',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='posts.images'),
        ),
        migrations.DeleteModel(
            name='BookmarkPost',
        ),
    ]
