# Generated by Django 4.0 on 2021-12-22 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_posts_file_remove_posts_user_post_and_more'),
        ('comments', '0004_alter_comments_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
