# Generated by Django 4.0 on 2021-12-22 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_rename_images_image'),
        ('comments', '0004_alter_comments_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
